export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_LOADING_FAILED = 'PROJECTS_LOADING_FAILED';
export const UPDATED_PROJECT = 'UPDATED_PROJECT';

export const SESSIONS_RECEIVED = 'SESSIONS_RECEIVED';
export const SESSIONS_LOADING = 'SESSIONS_LOADING';
export const SESSIONS_LOADING_FAILED = 'SESSIONS_LOADING_FAILED';

export const CREATED_SESSION = 'CREATED_SESSION';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
